export type GoalCategoryCode =
  | "physical"
  | "personality"
  | "family"
  | "expectations"
  | "language"
  | "studies";

export type GoalComparisonModel = "ordinal" | "equivalence" | "exact";
export type PreferenceValueSeed = {
  categoryCode: GoalCategoryCode;
  valueKey: string;
  labelEs: string;
  labelEn: string;
  sortOrder: number;
  ordinalRank?: number;
};

export const GOAL_CATEGORIES: Array<{
  code: GoalCategoryCode;
  labelEs: string;
  labelEn: string;
  sortOrder: number;
  comparisonModel: GoalComparisonModel;
  supportsModeDisplay: boolean;
  supportsGoalDerivation: boolean;
  supportsProgressCalculation: boolean;
  supportsTaskGeneration: boolean;
  thresholdLikeCount: number;
  goalEngineEnabled: boolean;
}> = [
  {
    code: "physical",
    labelEs: "Físicas",
    labelEn: "Physical",
    sortOrder: 0,
    comparisonModel: "ordinal",
    supportsModeDisplay: true,
    supportsGoalDerivation: true,
    supportsProgressCalculation: true,
    supportsTaskGeneration: true,
    thresholdLikeCount: 30,
    goalEngineEnabled: true,
  },
  {
    code: "personality",
    labelEs: "Personalidad",
    labelEn: "Personality",
    sortOrder: 1,
    comparisonModel: "equivalence",
    supportsModeDisplay: true,
    supportsGoalDerivation: false,
    supportsProgressCalculation: false,
    supportsTaskGeneration: false,
    thresholdLikeCount: 30,
    goalEngineEnabled: false,
  },
  {
    code: "family",
    labelEs: "Familia",
    labelEn: "Family",
    sortOrder: 2,
    comparisonModel: "exact",
    supportsModeDisplay: true,
    supportsGoalDerivation: true,
    supportsProgressCalculation: true,
    supportsTaskGeneration: true,
    thresholdLikeCount: 30,
    goalEngineEnabled: true,
  },
  {
    code: "expectations",
    labelEs: "Expectativas",
    labelEn: "Expectations",
    sortOrder: 3,
    comparisonModel: "exact",
    supportsModeDisplay: true,
    supportsGoalDerivation: true,
    supportsProgressCalculation: true,
    supportsTaskGeneration: true,
    thresholdLikeCount: 30,
    goalEngineEnabled: true,
  },
  {
    code: "language",
    labelEs: "Idioma",
    labelEn: "Language",
    sortOrder: 4,
    comparisonModel: "exact",
    supportsModeDisplay: true,
    supportsGoalDerivation: true,
    supportsProgressCalculation: true,
    supportsTaskGeneration: true,
    thresholdLikeCount: 30,
    goalEngineEnabled: true,
  },
  {
    code: "studies",
    labelEs: "Estudios",
    labelEn: "Studies",
    sortOrder: 5,
    comparisonModel: "ordinal",
    supportsModeDisplay: true,
    supportsGoalDerivation: true,
    supportsProgressCalculation: true,
    supportsTaskGeneration: true,
    thresholdLikeCount: 30,
    goalEngineEnabled: true,
  },
];

export const DEFAULT_GOAL_TEMPLATES = [
  {
    goalKey: "1",
    categoryCode: "physical",
    taskTemplateGroupKey: "default",
    titleEs: "Resistencia cardiovascular",
    titleEn: "Cardiovascular endurance",
    defaultSortOrder: 0,
    nextActionEs: "Corre 20 min hoy sin parar",
    nextActionEn: "Run 20 min today without stopping",
    impactEs: "Más energía y mejor postura",
    impactEn: "More energy and better posture",
  },
  {
    goalKey: "2",
    categoryCode: "personality",
    taskTemplateGroupKey: "default",
    titleEs: "Confianza social",
    titleEn: "Social confidence",
    defaultSortOrder: 0,
    nextActionEs: "Inicia una conversación con un extraño",
    nextActionEn: "Start a conversation with a stranger",
    impactEs: "Más atractivo en interacciones sociales",
    impactEn: "More attractive in social interactions",
  },
  {
    goalKey: "3",
    categoryCode: "physical",
    taskTemplateGroupKey: "default",
    titleEs: "Cuidado personal consistente",
    titleEn: "Consistent grooming routine",
    defaultSortOrder: 2,
    nextActionEs: "Mantén un ritual simple de autocuidado esta semana",
    nextActionEn: "Keep a simple self-care ritual this week",
    impactEs: "Refuerza tu presencia y seguridad personal",
    impactEn: "Reinforces your presence and self-confidence",
  },
  {
    goalKey: "4",
    categoryCode: "personality",
    taskTemplateGroupKey: "default",
    titleEs: "Inteligencia emocional",
    titleEn: "Emotional intelligence",
    defaultSortOrder: 2,
    nextActionEs: "Escucha activa en tu próxima conversación",
    nextActionEn: "Active listening in your next conversation",
    impactEs: "Conexiones más profundas y auténticas",
    impactEn: "Deeper and more authentic connections",
  },
  {
    goalKey: "5",
    categoryCode: "physical",
    taskTemplateGroupKey: "default",
    titleEs: "Postura corporal",
    titleEn: "Body posture",
    defaultSortOrder: 1,
    nextActionEs: "10 min de ejercicios de postura ahora",
    nextActionEn: "10 min posture exercises right now",
    impactEs: "Proyectas más confianza y presencia",
    impactEn: "Project more confidence and presence",
  },
  {
    goalKey: "6",
    categoryCode: "language",
    taskTemplateGroupKey: "default",
    titleEs: "Habilidades de conversación",
    titleEn: "Conversation skills",
    defaultSortOrder: 0,
    nextActionEs: "Aprende 3 preguntas abiertas interesantes",
    nextActionEn: "Learn 3 interesting open-ended questions",
    impactEs: "Conversaciones más atractivas y fluidas",
    impactEn: "More engaging and fluid conversations",
  },
  {
    goalKey: "7",
    categoryCode: "personality",
    taskTemplateGroupKey: "default",
    titleEs: "Límites personales claros",
    titleEn: "Clear personal boundaries",
    defaultSortOrder: 1,
    nextActionEs: "Define una situación donde quieras responder con más calma",
    nextActionEn: "Define one situation where you want to respond more calmly",
    impactEs: "Te ayuda a sentir más control y coherencia",
    impactEn: "Helps you feel more in control and aligned",
  },
  {
    goalKey: "8",
    categoryCode: "family",
    taskTemplateGroupKey: "default",
    titleEs: "Visión familiar clara",
    titleEn: "Clear family vision",
    defaultSortOrder: 0,
    nextActionEs: "Escribe qué significa familia para ti hoy",
    nextActionEn: "Write down what family means to you today",
    impactEs: "Aclara tus prioridades a largo plazo",
    impactEn: "Clarifies your long-term priorities",
  },
  {
    goalKey: "9",
    categoryCode: "family",
    taskTemplateGroupKey: "default",
    titleEs: "Conversación sobre hijxs",
    titleEn: "Children conversation",
    defaultSortOrder: 1,
    nextActionEs: "Prepara cómo hablarías de este tema con honestidad",
    nextActionEn: "Prepare how you would talk about this topic honestly",
    impactEs: "Reduce fricciones futuras y alinea expectativas",
    impactEn: "Reduces future friction and aligns expectations",
  },
  {
    goalKey: "10",
    categoryCode: "family",
    taskTemplateGroupKey: "default",
    titleEs: "Ritmo de estabilidad",
    titleEn: "Pace of stability",
    defaultSortOrder: 2,
    nextActionEs: "Piensa qué tipo de rutina compartida te hace sentir en paz",
    nextActionEn: "Think about what kind of shared routine gives you peace",
    impactEs: "Te acerca a vínculos más sostenibles",
    impactEn: "Moves you toward more sustainable bonds",
  },
  {
    goalKey: "11",
    categoryCode: "expectations",
    taskTemplateGroupKey: "default",
    titleEs: "Claridad romántica",
    titleEn: "Relationship clarity",
    defaultSortOrder: 0,
    nextActionEs: "Resume en una frase lo que buscas construir",
    nextActionEn: "Summarize in one sentence what you want to build",
    impactEs: "Hace tu intención más visible y coherente",
    impactEn: "Makes your intention more visible and consistent",
  },
  {
    goalKey: "12",
    categoryCode: "expectations",
    taskTemplateGroupKey: "default",
    titleEs: "No negociables sanos",
    titleEn: "Healthy non-negotiables",
    defaultSortOrder: 2,
    nextActionEs: "Anota los tres valores que no quieres comprometer",
    nextActionEn: "Write down the three values you do not want to compromise",
    impactEs: "Refuerza decisiones más conscientes",
    impactEn: "Supports more intentional decisions",
  },
  {
    goalKey: "13",
    categoryCode: "expectations",
    taskTemplateGroupKey: "default",
    titleEs: "Ritmo consciente",
    titleEn: "Intentional pacing",
    defaultSortOrder: 1,
    nextActionEs: "Define el ritmo que se siente sano para ti al conocer a alguien",
    nextActionEn: "Define the pace that feels healthy for you when meeting someone",
    impactEs: "Genera más control emocional y claridad",
    impactEn: "Creates more emotional control and clarity",
  },
  {
    goalKey: "14",
    categoryCode: "language",
    taskTemplateGroupKey: "default",
    titleEs: "Presentación natural",
    titleEn: "Natural self-introduction",
    defaultSortOrder: 2,
    nextActionEs: "Practica una introducción breve que suene auténtica",
    nextActionEn: "Practice a short introduction that sounds authentic",
    impactEs: "Te hace sonar más seguro desde el inicio",
    impactEn: "Makes you sound more confident from the start",
  },
  {
    goalKey: "15",
    categoryCode: "language",
    taskTemplateGroupKey: "default",
    titleEs: "Escucha activa verbal",
    titleEn: "Verbal active listening",
    defaultSortOrder: 1,
    nextActionEs: "Prueba una frase de validación en tu próxima charla",
    nextActionEn: "Try one validation phrase in your next conversation",
    impactEs: "Aumenta conexión y reciprocidad",
    impactEn: "Improves connection and reciprocity",
  },
  {
    goalKey: "16",
    categoryCode: "studies",
    taskTemplateGroupKey: "default",
    titleEs: "Historia profesional clara",
    titleEn: "Clear learning story",
    defaultSortOrder: 2,
    nextActionEs: "Resume tu recorrido de estudio o aprendizaje en dos líneas",
    nextActionEn: "Summarize your study or learning path in two lines",
    impactEs: "Hace tu perfil más nítido y memorable",
    impactEn: "Makes your profile sharper and more memorable",
  },
  {
    goalKey: "17",
    categoryCode: "studies",
    taskTemplateGroupKey: "default",
    titleEs: "Plan de crecimiento",
    titleEn: "Growth plan",
    defaultSortOrder: 0,
    nextActionEs: "Elige una habilidad que quieras reforzar este mes",
    nextActionEn: "Choose one skill you want to strengthen this month",
    impactEs: "Transmite ambición tranquila y dirección",
    impactEn: "Signals calm ambition and direction",
  },
  {
    goalKey: "18",
    categoryCode: "studies",
    taskTemplateGroupKey: "default",
    titleEs: "Mostrar tu especialidad",
    titleEn: "Show your expertise",
    defaultSortOrder: 1,
    nextActionEs: "Piensa cómo explicarías tu fortaleza principal con claridad",
    nextActionEn: "Think about how you would explain your main strength clearly",
    impactEs: "Te ayuda a destacar con naturalidad",
    impactEn: "Helps you stand out naturally",
  },
] as const;

export const DEFAULT_PREFERENCE_VALUES: PreferenceValueSeed[] = [
  { categoryCode: "physical", valueKey: "slim", labelEs: "Delgado", labelEn: "Slim", sortOrder: 0, ordinalRank: 0 },
  { categoryCode: "physical", valueKey: "lean", labelEs: "Esbelto", labelEn: "Lean", sortOrder: 1, ordinalRank: 1 },
  { categoryCode: "physical", valueKey: "athletic", labelEs: "Atlético", labelEn: "Athletic", sortOrder: 2, ordinalRank: 2 },
  { categoryCode: "physical", valueKey: "muscular", labelEs: "Musculoso", labelEn: "Muscular", sortOrder: 3, ordinalRank: 3 },
  { categoryCode: "physical", valueKey: "medium_build", labelEs: "Complexión media", labelEn: "Medium build", sortOrder: 4, ordinalRank: 4 },
  { categoryCode: "physical", valueKey: "compact_build", labelEs: "Compacto", labelEn: "Compact build", sortOrder: 5, ordinalRank: 5 },
  { categoryCode: "physical", valueKey: "curvy", labelEs: "Curvilíneo", labelEn: "Curvy", sortOrder: 6, ordinalRank: 6 },
  { categoryCode: "physical", valueKey: "rounded_build", labelEs: "Cuerpo redondeado", labelEn: "Rounded build", sortOrder: 7, ordinalRank: 7 },
  { categoryCode: "physical", valueKey: "sturdy", labelEs: "Robusto", labelEn: "Sturdy", sortOrder: 8, ordinalRank: 8 },
  { categoryCode: "physical", valueKey: "large_build", labelEs: "Complexión grande", labelEn: "Large build", sortOrder: 9, ordinalRank: 9 },
  { categoryCode: "physical", valueKey: "plus_size", labelEs: "Plus-size", labelEn: "Plus size", sortOrder: 10, ordinalRank: 10 },

  { categoryCode: "family", valueKey: "want_children", labelEs: "Quiere hijos", labelEn: "Wants children", sortOrder: 0 },
  { categoryCode: "family", valueKey: "have_and_want_more", labelEs: "Tiene y quiere más", labelEn: "Has and wants more", sortOrder: 1 },
  { categoryCode: "family", valueKey: "have_and_dont_want_more", labelEs: "Tiene y no quiere más", labelEn: "Has and does not want more", sortOrder: 2 },
  { categoryCode: "family", valueKey: "not_sure", labelEs: "No está seguro", labelEn: "Not sure", sortOrder: 3 },
  { categoryCode: "family", valueKey: "dont_want_children", labelEs: "No quiere hijos", labelEn: "Does not want children", sortOrder: 4 },

  { categoryCode: "expectations", valueKey: "stable_relationship", labelEs: "Relación estable", labelEn: "Stable relationship", sortOrder: 0 },
  { categoryCode: "expectations", valueKey: "still_figuring_it_out", labelEs: "Aún lo está descubriendo", labelEn: "Still figuring it out", sortOrder: 1 },
  { categoryCode: "expectations", valueKey: "making_friends", labelEs: "Hacer amistades", labelEn: "Making friends", sortOrder: 2 },
  { categoryCode: "expectations", valueKey: "nothing_serious", labelEs: "Nada serio", labelEn: "Nothing serious", sortOrder: 3 },

  { categoryCode: "language", valueKey: "es", labelEs: "Español", labelEn: "Spanish", sortOrder: 0 },
  { categoryCode: "language", valueKey: "en", labelEs: "Inglés", labelEn: "English", sortOrder: 1 },
  { categoryCode: "language", valueKey: "fr", labelEs: "Francés", labelEn: "French", sortOrder: 2 },
  { categoryCode: "language", valueKey: "de", labelEs: "Alemán", labelEn: "German", sortOrder: 3 },
  { categoryCode: "language", valueKey: "it", labelEs: "Italiano", labelEn: "Italian", sortOrder: 4 },
  { categoryCode: "language", valueKey: "pt", labelEs: "Portugués", labelEn: "Portuguese", sortOrder: 5 },
  { categoryCode: "language", valueKey: "ca", labelEs: "Catalán", labelEn: "Catalan", sortOrder: 6 },
  { categoryCode: "language", valueKey: "ja", labelEs: "Japonés", labelEn: "Japanese", sortOrder: 7 },

  { categoryCode: "studies", valueKey: "high_school", labelEs: "Secundaria", labelEn: "High school", sortOrder: 0, ordinalRank: 0 },
  { categoryCode: "studies", valueKey: "technical_school", labelEs: "Formación técnica", labelEn: "Technical school", sortOrder: 1, ordinalRank: 1 },
  { categoryCode: "studies", valueKey: "university_student", labelEs: "Estudiante universitario", labelEn: "University student", sortOrder: 2, ordinalRank: 2 },
  { categoryCode: "studies", valueKey: "bachelors_degree", labelEs: "Licenciatura", labelEn: "Bachelor's degree", sortOrder: 3, ordinalRank: 3 },
  { categoryCode: "studies", valueKey: "masters_degree", labelEs: "Máster", labelEn: "Master's degree", sortOrder: 4, ordinalRank: 4 },
  { categoryCode: "studies", valueKey: "doctorate", labelEs: "Doctorado", labelEn: "Doctorate", sortOrder: 5, ordinalRank: 5 },
];

export const DEFAULT_CATEGORY_GOAL_RULES = GOAL_CATEGORIES.map((category) => ({
  categoryCode: category.code,
  ruleKey: "default",
  gapMin: 0,
  gapMax: 1000,
  targetSelectionStrategy: "mode_value",
  progressFormulaType: "category_default",
  taskTemplateGroupKey: "default",
  isActive: true,
}));
