export type GoalCategoryCode =
  | "physical"
  | "personality"
  | "family"
  | "expectations"
  | "language"
  | "studies";

export const GOAL_CATEGORIES: Array<{
  code: GoalCategoryCode;
  labelEs: string;
  labelEn: string;
  sortOrder: number;
}> = [
  { code: "physical", labelEs: "Físicas", labelEn: "Physical", sortOrder: 0 },
  {
    code: "personality",
    labelEs: "Personalidad",
    labelEn: "Personality",
    sortOrder: 1,
  },
  { code: "family", labelEs: "Familia", labelEn: "Family", sortOrder: 2 },
  {
    code: "expectations",
    labelEs: "Expectativas",
    labelEn: "Expectations",
    sortOrder: 3,
  },
  { code: "language", labelEs: "Idioma", labelEn: "Language", sortOrder: 4 },
  { code: "studies", labelEs: "Estudios", labelEn: "Studies", sortOrder: 5 },
];

export const DEFAULT_GOAL_TEMPLATES = [
  {
    goalKey: "1",
    categoryCode: "physical",
    titleEs: "Resistencia cardiovascular",
    titleEn: "Cardiovascular endurance",
    defaultSortOrder: 0,
    nextActionEs: "Corre 20 min hoy sin parar",
    nextActionEn: "Run 20 min today without stopping",
    impactEs: "Más energía y mejor postura",
    impactEn: "More energy and better posture",
  },
  {
    goalKey: "2",
    categoryCode: "personality",
    titleEs: "Confianza social",
    titleEn: "Social confidence",
    defaultSortOrder: 0,
    nextActionEs: "Inicia una conversación con un extraño",
    nextActionEn: "Start a conversation with a stranger",
    impactEs: "Más atractivo en interacciones sociales",
    impactEn: "More attractive in social interactions",
  },
  {
    goalKey: "3",
    categoryCode: "physical",
    titleEs: "Cuidado personal consistente",
    titleEn: "Consistent grooming routine",
    defaultSortOrder: 2,
    nextActionEs: "Mantén un ritual simple de autocuidado esta semana",
    nextActionEn: "Keep a simple self-care ritual this week",
    impactEs: "Refuerza tu presencia y seguridad personal",
    impactEn: "Reinforces your presence and self-confidence",
  },
  {
    goalKey: "4",
    categoryCode: "personality",
    titleEs: "Inteligencia emocional",
    titleEn: "Emotional intelligence",
    defaultSortOrder: 2,
    nextActionEs: "Escucha activa en tu próxima conversación",
    nextActionEn: "Active listening in your next conversation",
    impactEs: "Conexiones más profundas y auténticas",
    impactEn: "Deeper and more authentic connections",
  },
  {
    goalKey: "5",
    categoryCode: "physical",
    titleEs: "Postura corporal",
    titleEn: "Body posture",
    defaultSortOrder: 1,
    nextActionEs: "10 min de ejercicios de postura ahora",
    nextActionEn: "10 min posture exercises right now",
    impactEs: "Proyectas más confianza y presencia",
    impactEn: "Project more confidence and presence",
  },
  {
    goalKey: "6",
    categoryCode: "language",
    titleEs: "Habilidades de conversación",
    titleEn: "Conversation skills",
    defaultSortOrder: 0,
    nextActionEs: "Aprende 3 preguntas abiertas interesantes",
    nextActionEn: "Learn 3 interesting open-ended questions",
    impactEs: "Conversaciones más atractivas y fluidas",
    impactEn: "More engaging and fluid conversations",
  },
  {
    goalKey: "7",
    categoryCode: "personality",
    titleEs: "Límites personales claros",
    titleEn: "Clear personal boundaries",
    defaultSortOrder: 1,
    nextActionEs: "Define una situación donde quieras responder con más calma",
    nextActionEn: "Define one situation where you want to respond more calmly",
    impactEs: "Te ayuda a sentir más control y coherencia",
    impactEn: "Helps you feel more in control and aligned",
  },
  {
    goalKey: "8",
    categoryCode: "family",
    titleEs: "Visión familiar clara",
    titleEn: "Clear family vision",
    defaultSortOrder: 0,
    nextActionEs: "Escribe qué significa familia para ti hoy",
    nextActionEn: "Write down what family means to you today",
    impactEs: "Aclara tus prioridades a largo plazo",
    impactEn: "Clarifies your long-term priorities",
  },
  {
    goalKey: "9",
    categoryCode: "family",
    titleEs: "Conversación sobre hijxs",
    titleEn: "Children conversation",
    defaultSortOrder: 1,
    nextActionEs: "Prepara cómo hablarías de este tema con honestidad",
    nextActionEn: "Prepare how you would talk about this topic honestly",
    impactEs: "Reduce fricciones futuras y alinea expectativas",
    impactEn: "Reduces future friction and aligns expectations",
  },
  {
    goalKey: "10",
    categoryCode: "family",
    titleEs: "Ritmo de estabilidad",
    titleEn: "Pace of stability",
    defaultSortOrder: 2,
    nextActionEs: "Piensa qué tipo de rutina compartida te hace sentir en paz",
    nextActionEn: "Think about what kind of shared routine gives you peace",
    impactEs: "Te acerca a vínculos más sostenibles",
    impactEn: "Moves you toward more sustainable bonds",
  },
  {
    goalKey: "11",
    categoryCode: "expectations",
    titleEs: "Claridad romántica",
    titleEn: "Relationship clarity",
    defaultSortOrder: 0,
    nextActionEs: "Resume en una frase lo que buscas construir",
    nextActionEn: "Summarize in one sentence what you want to build",
    impactEs: "Hace tu intención más visible y coherente",
    impactEn: "Makes your intention more visible and consistent",
  },
  {
    goalKey: "12",
    categoryCode: "expectations",
    titleEs: "No negociables sanos",
    titleEn: "Healthy non-negotiables",
    defaultSortOrder: 2,
    nextActionEs: "Anota los tres valores que no quieres comprometer",
    nextActionEn: "Write down the three values you do not want to compromise",
    impactEs: "Refuerza decisiones más conscientes",
    impactEn: "Supports more intentional decisions",
  },
  {
    goalKey: "13",
    categoryCode: "expectations",
    titleEs: "Ritmo consciente",
    titleEn: "Intentional pacing",
    defaultSortOrder: 1,
    nextActionEs: "Define el ritmo que se siente sano para ti al conocer a alguien",
    nextActionEn: "Define the pace that feels healthy for you when meeting someone",
    impactEs: "Genera más control emocional y claridad",
    impactEn: "Creates more emotional control and clarity",
  },
  {
    goalKey: "14",
    categoryCode: "language",
    titleEs: "Presentación natural",
    titleEn: "Natural self-introduction",
    defaultSortOrder: 2,
    nextActionEs: "Practica una introducción breve que suene auténtica",
    nextActionEn: "Practice a short introduction that sounds authentic",
    impactEs: "Te hace sonar más seguro desde el inicio",
    impactEn: "Makes you sound more confident from the start",
  },
  {
    goalKey: "15",
    categoryCode: "language",
    titleEs: "Escucha activa verbal",
    titleEn: "Verbal active listening",
    defaultSortOrder: 1,
    nextActionEs: "Prueba una frase de validación en tu próxima charla",
    nextActionEn: "Try one validation phrase in your next conversation",
    impactEs: "Aumenta conexión y reciprocidad",
    impactEn: "Improves connection and reciprocity",
  },
  {
    goalKey: "16",
    categoryCode: "studies",
    titleEs: "Historia profesional clara",
    titleEn: "Clear learning story",
    defaultSortOrder: 2,
    nextActionEs: "Resume tu recorrido de estudio o aprendizaje en dos líneas",
    nextActionEn: "Summarize your study or learning path in two lines",
    impactEs: "Hace tu perfil más nítido y memorable",
    impactEn: "Makes your profile sharper and more memorable",
  },
  {
    goalKey: "17",
    categoryCode: "studies",
    titleEs: "Plan de crecimiento",
    titleEn: "Growth plan",
    defaultSortOrder: 0,
    nextActionEs: "Elige una habilidad que quieras reforzar este mes",
    nextActionEn: "Choose one skill you want to strengthen this month",
    impactEs: "Transmite ambición tranquila y dirección",
    impactEn: "Signals calm ambition and direction",
  },
  {
    goalKey: "18",
    categoryCode: "studies",
    titleEs: "Mostrar tu especialidad",
    titleEn: "Show your expertise",
    defaultSortOrder: 1,
    nextActionEs: "Piensa cómo explicarías tu fortaleza principal con claridad",
    nextActionEn: "Think about how you would explain your main strength clearly",
    impactEs: "Te ayuda a destacar con naturalidad",
    impactEn: "Helps you stand out naturally",
  },
] as const;
