export const ANALYTICS_EVENT_NAMES = [
  "app_opened",
  "app_foregrounded",
  "app_backgrounded",
  "session_started",
  "session_heartbeat",
  "session_ended",
  "screen_time",
  "logout_clicked",
  "sign_up_started",
  "sign_up_completed",
  "login_success",
  "login_failed",
  "email_verification_required",
  "onboarding_started",
  "onboarding_step_viewed",
  "onboarding_step_completed",
  "onboarding_completed",
  "onboarding_abandoned",
  "complete_profile_required",
  "profile_completion_completed",
  "onboarding_gate_denied",
  "discover_opened",
  "discovery_window_requested",
  "discovery_window_loaded",
  "discovery_window_failed",
  "profile_card_shown",
  "profile_card_visible_duration",
  "profile_info_opened",
  "profile_info_closed",
  "profile_photo_viewed",
  "profile_like",
  "profile_pass",
  "discovery_decision_success",
  "discovery_decision_failed",
  "discovery_queue_exhausted",
  "discovery_repeated_profile_anomaly",
  "discovery_filter_opened",
  "discovery_filter_changed",
  "discovery_filter_cleared",
  "goals_tab_opened",
  "goals_locked_viewed",
  "threshold_progress_viewed",
  "threshold_unlock_modal_shown",
  "threshold_unlock_cta_clicked",
  "goals_unlocked",
  "goal_card_viewed",
  "goal_detail_opened",
  "goal_task_started",
  "goal_task_completed",
  "goal_task_skipped",
  "returning_user_opened_app",
  "api_request_failed",
  "offline_detected",
  "server_unreachable",
  "auth_refresh_failed",
  "media_load_failed",
  "decision_latency_slow",
  "image_load_latency_slow",
  "onboarding_save_failed",
  "profile_save_failed",
] as const;

export const ANALYTICS_METADATA_KEYS = [
  "step",
  "stepIndex",
  "stepName",
  "source",
  "reason",
  "status",
  "count",
  "queueVersion",
  "policyVersion",
  "requestId",
  "decision",
  "action",
  "latencyMs",
  "httpStatus",
  "errorCode",
  "isOnline",
  "profileCount",
  "likes",
  "passes",
  "totalLikes",
  "thresholdReached",
  "filtersChanged",
  "selectedGendersCount",
  "therianMode",
  "ageMin",
  "ageMax",
  "photoIndex",
  "photosViewed",
  "openedInfo",
  "targetProfileKind",
  "targetProfileBatchKey",
  "endedBy",
  "route",
  "fromRoute",
  "toRoute",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];
export type AnalyticsPlatform = "ios" | "android" | "web";

export type AnalyticsContext = {
  sessionId?: string | null;
  platform?: AnalyticsPlatform | null;
  appVersion?: string | null;
  buildNumber?: string | null;
  deviceFamily?: string | null;
};
